// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqE-47LcQtL9gNKQl4NwKWExowgpLHKsA',
    appId: '1:172840270905:web:f6927fe0182c5e8aa5e1e8',
    messagingSenderId: '172840270905',
    projectId: 'biotrail-99f38',
    authDomain: 'biotrail-99f38.firebaseapp.com',
    storageBucket: 'biotrail-99f38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATI_-zkeoRNznS892XzSFO3c3M719KRZg',
    appId: '1:172840270905:android:3739fe19d22b4bf7a5e1e8',
    messagingSenderId: '172840270905',
    projectId: 'biotrail-99f38',
    storageBucket: 'biotrail-99f38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-T4ROJuLzHvEx3FDgwuzr8A_QQLBkztM',
    appId: '1:172840270905:ios:754e07d8eb0a00eba5e1e8',
    messagingSenderId: '172840270905',
    projectId: 'biotrail-99f38',
    storageBucket: 'biotrail-99f38.firebasestorage.app',
    iosBundleId: 'com.example.bioTrail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-T4ROJuLzHvEx3FDgwuzr8A_QQLBkztM',
    appId: '1:172840270905:ios:754e07d8eb0a00eba5e1e8',
    messagingSenderId: '172840270905',
    projectId: 'biotrail-99f38',
    storageBucket: 'biotrail-99f38.firebasestorage.app',
    iosBundleId: 'com.example.bioTrail',
  );
}
